manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: rianadon
      url-base: https://github.com/rianadon
    - name: pedantic
      url-base: https://github.com/PedanticAvenger
  projects:
    - name: zmk
      remote: rianadon
      revision: main
      import: app/west.yml
    - name: zmk-dongle-screen
      remote: pedantic
      revision: main
  self:
    path: config
    import: deps.yml
